version: '1'
services:
  web:
    build: ./apis
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
  mysql:
    image: "mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=test123123"
      - "MYSQL_DATABASE=coupon"
      - "TZ=Asia/Shanghai"
  mongodb:
    image: "mongo"